### ISSUE TITLE
Can't remove existing team members?

### ISSUE THREAD

**Issue by philfreo** [timezoneio/timezoneio#19]
I added a team member (I think under a fake email address) to test out timezone.io some time ago. I'm trying to setup a team now and I can't find a way to delete/edit that team member.

From the code it seems that you should just be able to click the person to edit them, but that's not doing anything. Am I doing something wrong, or is this a bug?

**Comment by djfarrelly** [comment]
Hi @philfreo! When managing your team (clicking the cog at the top from your team's page) you should have an X next to team members (see below). Do you see this X? If not, what browser are you using and 
what steps are you taking?

<img width="579" alt="screenshot 2016-04-30 18 14 55" src="https://cloud.githubusercontent.com/assets/1509457/14938839/8bb846de-0eff-11e6-9648-cdb76a584549.png">

**Comment by philfreo** [comment]
I don't see anything but the search box on the right side.

Chrome 50 OS X

**Comment by djfarrelly** [comment]
Alright, that sounds like a strange bug that it's not even rendering the edit UI for you @philfreo. I'm going to look into this straight away!

**Comment by djfarrelly** [comment]
Hi @philfreo, in a help to debug this issue, I've added some debug code on production. I wonder if you could perhaps head over to manage your team (http://timezone.io/team/closeio/manage) and open up the console and send me the dump of data there and perhaps let me know of any errors you might see there. You can drop the info here or email me: **hi [at] timezone.io** if you'd rather do that. Thanks so much for your help!

**Comment by philfreo** [comment]
![screenshot 2016-05-01 09 00 53](https://cloud.githubusercontent.com/assets/97612/14942748/3ceae314-0f7b-11e6-91a0-92f439da3938.png)

**Comment by djfarrelly** [comment]
Thanks @philfreo! That's strange, it looks like a css/layout issue with that gray bar showing there like that. It's using a bunch of flexbox which might have a layout issue, but it's looking normal in Chrome 50 for me. I'll keep digging into this, but if you have any free moments, I'd love to see what the dom looks like in that div, my gut is telling me it's a css issue though, but it's hard not being able to reproduce! Will keep trying on my end 👍

**Comment by philfreo** [comment]
Ah! Removing `max-height: 100%;` from `.manage-team--team-list` fixes it!

**Comment by philfreo** [comment]
OS X Version 50.0.2661.94 (64-bit)

**Comment by djfarrelly** [comment]
@philfreo, you are the man! I'll work with that and make the change ASAP!
