### ISSUE TITLE
Incorrect timezone in Chile

### ISSUE THREAD

**Issue by marioperezpereira** [timezoneio/timezoneio#35]
Hi, Chile has entered into summer time, it's one hour less than it's on the platform ;)

**Comment by djfarrelly** [comment]
Thanks @marioperezpereira, I think my timezone data is a bit old, will try to update it asap!

**Comment by djfarrelly** [comment]
Sorry for the delay @marioperezpereira, the timezone database is updated so Santiago is fixed :)

**Comment by marioperezpereira** [comment]
Thx!
