### ISSUE TITLE
Create public-facing version of timezone.io

### ISSUE THREAD

**Issue by BlackVegetable** [timezoneio/timezoneio#37]
Timezone.io could be an interesting way for a company to showcase the fact that it has many remote workers (and where they are).  To do this, a view of the company would have to be visible to the public, should an option (opt-in) be enabled to present such.

**Comment by djfarrelly** [comment]
Hey @BlackVegetable, currently all companies are public. Currently, permissions are on the per-user basis for location privacy. You can currently link to your team from anywhere :)

Example: https://timezone.io/team/discourse

**Comment by BlackVegetable** [comment]
That's incredible; I don't know how I didn't realize that.  Thank you.  We will make sure everyone remote in our company adds themselves and show it to the world.  Thanks!

**Comment by djfarrelly** [comment]
Awesome @BlackVegetable! Thanks for the support!!
