### ISSUE TITLE
"Save changes" button deletes account

### ISSUE THREAD

**Issue by dmitryn** [timezoneio/timezoneio#56]
On account page https://timezone.io/account clicking on "Save changes" deletes account.

**Comment by Flydancer** [comment]
happened to me, too. please fix this asap. It's very annoying because the whole team gets also deleted

**Comment by hariso** [comment]
This happened to me a minute ago...

**Comment by myaskevich** [comment]
Crazy!

**Comment by hariso** [comment]
> Crazy!
What's even crazier is that, on the same page, the option for deleting requires that you confirm it a second time. But clicking "Save" just deletes it. No confirmation, no nothing.

It's a great concern that this is open for already two weeks, without any response from Timezone.io.

**Comment by myaskevich** [comment]
@dmitryn looks like this is no longer the issue
