### ISSUE TITLE
Account gets deleted when changing location to private

### ISSUE THREAD

**Issue by bigdaz** [timezoneio/timezoneio#60]
I clicked "edit profile", and set my location privacy setting to "my team only".
The result: "Your account has been deleted. Sorry to see you go."

Not what I was hoping for :). This happened for me twice, and independently for a colleague.

![image 2](https://user-images.githubusercontent.com/179734/36909068-528d2290-1e3d-11e8-981a-052d66c4c0a0.png)

**Comment by djfarrelly** [comment]
I'm sorry about this one. I've just merged and deployed the fix in #59!
