### ISSUE TITLE
Location shown as "NULL", when location is hidden

### ISSUE THREAD

**Issue by aliok** [timezoneio/timezoneio#64]
When I select "Only show my local time - hide my location for everyone but me" option in account settings, my location is shown as NULL. It is shown that way to me and others in the team.

Account settings:
![screenshot from 2018-03-07 13-35-46](https://user-images.githubusercontent.com/376732/37087849-8a27c7dc-220c-11e8-8955-0ba84fbf66aa.png)

Team view:
![screenshot from 2018-03-07 13-35-16](https://user-images.githubusercontent.com/376732/37087841-885e4a98-220c-11e8-90e5-8cbbcf6139d1.png)

**Comment by patrickdaze** [comment]
Working on it. Will submit a PR soon
