### ISSUE TITLE
UPLOAD PHOTO NOT WORKING

### ISSUE THREAD

**Issue by lw2020** [timezoneio/timezoneio#70]
we neeed our photos up for quickness telling who is who and nobody can successfully upload their pics

**Comment by inheinsight** [comment]
I am also noticing this error. Though I can upload the image, after saving or navigating away from the upload session it just show's the below image. 
<img width="285" alt="image 2018-07-20 at 10 06 03 am" src="https://user-images.githubusercontent.com/30059474/43009910-9d0bec18-8c04-11e8-8751-77b3c98e07d3.png">

**Comment by fyi2** [comment]
Same issue.

**Comment by shannamceachern** [comment]
Is there an answer to this? Same issue today

**Comment by JezLouise** [comment]
Shame this is still not fixed :(

**Comment by mlebarron** [comment]
Just tried getting people in my company on board and upload still not working. I'm the only one with a gravatar :(

**Comment by tanyapampalone** [comment]
We're also having a problem with photo uploads. Any updates on this?

**Comment by stephenhutson** [comment]
I'm also having this problem and reached out on Twitter. Haven't gotten a response from the Timezone team. Where are you guys?

**Comment by tanyapampalone** [comment]
No reply!

Tanya Pampalone
tanyapampalone.com
@tanyapampalone
073 443 6464

**Comment by djfarrelly** [comment]
Sorry for the long running issue everyone! I finally got to the bottom of this and ran a script to resize all previously uploaded avatars so they should be fixed!
